version: '3'
services:
    caddy:
        image: caddy:2.1.1-alpine
        ports:
        - "127.0.0.1:8080:8080"
        restart: unless-stopped
        volumes:
        - .Caddyfile:/etc/caddy/Caddyfile
    reina-model:
        build:
            context: .
        restart: unless-stopped
        environment:
            - REDIS_URL=redis://redis:6379
            - FLASK_APP=graphql_backend.py
        # If we want to examine graphql API directly, without proxying
        ports:
            - "127.0.0.1:5000:5000"
        depends_on:
            - redis
        volumes:
            - .:/app
    redis:
        image: redis
        restart: unless-stopped
    reina-ui:
        build:
            context: ../reina-ui
        restart: unless-stopped
        # If we want to access Next.js server directly, without proxying
        # ports:
        #     - "127.0.0.1:3001:3000"
        # For some reason, .env file does not work automatically, like it
        # does for reina-model, so we're setting it explicitly here.
        env_file:
            - .env
        volumes:
            - ../reina-ui:/app
            - node_modules:/app/node_modules
volumes:
    node_modules:
